import React, { useState } from "react";
import Head from "next/head";
import { ColorModeScript, Center } from "@chakra-ui/react";
import theme from "../utilities/theme";
import Navbar from "../components/navbar";
import CountriesGrid from "../components/countriesGrid";
import Filtering from "../components/filtering";
import { useDebounce } from "use-debounce";

export default function Home() {
  const [searchPhrase, setSearchPhrase] = useState("");
  const [region, setRegion] = useState("");
  const [debouncedSearchPhrase] = useDebounce(searchPhrase, 300);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      <Navbar />
      <Center>
        <Filtering setSearchPhrase={setSearchPhrase} setRegion={setRegion} />
      </Center>
      <main>
        <Center>
          <CountriesGrid searchPhrase={debouncedSearchPhrase} region={region} />
        </Center>
      </main>

      <footer></footer>
    </div>
  );
}
