import Head from "next/head";
import { ColorModeScript, Center } from "@chakra-ui/react";
import theme from "../utilities/theme";
import Navbar from "../components/navbar";
import CountriesGrid from "../components/countriesGrid";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ColorModeScript initialColorMode={theme.config.initialColorMode} />
      <Navbar />
      <main>
        <Center>
          <CountriesGrid />
        </Center>
      </main>

      <footer></footer>
    </div>
  );
}
